# Build stage
FROM golang:1.22.4-alpine AS builder
WORKDIR /app
COPY src/ .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/app/main.go

# Final stage
FROM alpine:latest
# RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/main .
COPY --from=builder /app/.env .
COPY src/.air.toml .air.toml
EXPOSE 8080
CMD ["./main"]